extends: eslint:recommended

parserOptions:
  ecmaVersion: 5

env:
  browser: true
  node: false

rules:
  no-console: off
  comma-dangle:
    - error
    - only-multiline
  indent:
    - error
    - 2

globals:
  Promise: true
